Program.cs
appsettings.json

feat: merge multiple sources

---

MergerLogic/Extensions/ServiceCollectionExtensions.cs
MergerLogic/ImageProcessing/IImageFormatter.cs
MergerLogic/ImageProcessing/ImageFormatter.cs
MergerLogic/ImageProcessing/TileMerger.cs
MergerLogic/Utils/PathUtils.cs

feat: force image to png format

---

MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/DataTypes/Gpkg.cs
MergerLogic/DataTypes/S3.cs
MergerLogic/Utils/GpkgUtils.cs
MergerLogicUnitTests/DataTypes/FSTest.cs
MergerLogicUnitTests/DataTypes/GpkgTest.cs
MergerLogicUnitTests/DataTypes/S3Test.cs

Base data logger

---

MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/DataTypes/HttpDataSource.cs
MergerLogic/DataTypes/S3.cs
MergerLogicUnitTests/DataTypes/TMSTest.cs
MergerLogicUnitTests/DataTypes/WMTSTest.cs
MergerLogicUnitTests/DataTypes/XYZTest.cs

test: Http sources unit tests

---

MergerLogic/Batching/BlobTile.cs
MergerLogic/DataTypes/Gpkg.cs
MergerLogic/Utils/GpkgUtils.cs
MergerLogic/Utils/IGpkgUtils.cs
MergerLogicUnitTests/DataTypes/FSTest.cs
MergerLogicUnitTests/DataTypes/GpkgTest.cs
MergerLogicUnitTests/DataTypes/S3Test.cs
MergerLogicUnitTests/DataTypes/TMSTest.cs
MergerLogicUnitTests/DataTypes/WMTSTest.cs
MergerLogicUnitTests/DataTypes/XYZTest.cs
MergerLogicUnitTests/Utils/GpkgUtilsTest.cs
MergerLogicUnitTests/testUtils/ComparerFactory.cs
MergerLogicUnitTests/testUtils/DynamicDataGenerator.cs
MergerLogicUnitTests/testUtils/EqualityComparerFactory.cs

test: Gpkg utils tests

---

MergerLogic/DataTypes/S3.cs
MergerLogic/Utils/IDataUtils.cs
MergerLogic/Utils/IPathUtils.cs
MergerLogic/Utils/PathUtils.cs
MergerLogic/Utils/S3Utils.cs
MergerLogicUnitTests/Utils/S3UtilsTest.cs

S3 utils tests

---

MergerLogicUnitTests/Utils/GpkgUtilsTest.cs

test: added some missing gpkg utils unit tests

---

MergerLogic/Utils/StringUtils.cs
MergerLogicUnitTests/Utils/GeoUtilsTest.cs

test: geo utils unit test

---

MergerLogic/Utils/PathUtils.cs
MergerLogicUnitTests/Utils/PathUtilsTest.cs

test: path utils unit test

---

MergerLogic/Utils/OneXOneConvertor.cs
MergerLogicUnitTests/Utils/OneXOneConvertorTest.cs
MergerLogicUnitTests/testUtils/TestExpected.cs

test: 1X1 convertor unit tests

---

MergerLogic/Utils/PathPatternUtils.cs
MergerLogicUnitTests/Utils/PathPatternUtilsTest.cs

Path pattern utils unit test

---

MergerLogic/DataTypes/Gpkg.cs
MergerLogic/Extensions/DoubleExtenstion.cs
MergerLogic/Utils/GpkgUtils.cs
MergerLogic/Utils/IGpkgUtils.cs
MergerLogicUnitTests/DataTypes/GpkgTest.cs
MergerLogicUnitTests/Utils/GpkgUtilsTest.cs

feat: gpkg grid validation

---

helm/templates/deployment.yaml

chore: added node affinity

---

helm/templates/deployment.yaml
helm/values.yaml

fix: added node affinity use condition

---

helm/templates/configmap.yaml

fix: overseer config

---

helm/values.yaml

chore: use umbrella value naming

---

MergerService/appsettings.Development.json
helm/templates/configmap.yaml
helm/templates/deployment.yaml
helm/values.yaml

chore(helm): use different output paths for gpkg and files

---

MergerService/appsettings.Development.json
MergerService/appsettings.json
MergerService/src/run.cs
helm/templates/configmap.yaml

chore: start with empty configuration for task and job types

---

MergerService/appsettings.Development.json
MergerService/appsettings.json
MergerService/src/run.cs
helm/templates/deployment.yaml
helm/values.yaml

Input path

---

helm/templates/deployment.yaml

fix: volumes

---

MergerLogic/Utils/HttpRequestUtils.cs
MergerService/src/run.cs

refactor: on Http not found of task log as debug

---

MergerLogicUnitTests/Utils/HttpSourceUtilsTest.cs

test: added http utills test

---

MergerService/Models/Source.cs
MergerService/src/run.cs
helm/templates/deployment.yaml
helm/values.yaml

fix: source extent

---

MergerCli/appsettings.json
MergerLogic/Extensions/ServiceCollectionExtensions.cs
MergerLogic/MergerLogic.csproj
MergerLogic/Utils/HttpRequestUtils.cs
MergerService/appsettings.json
helm/templates/configmap.yaml
helm/values.yaml

feat: added http retry support

---

MergerCli/SourceParser.cs
MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/DataTypes/Gpkg.cs
MergerLogic/DataTypes/HttpDataSource.cs
MergerLogic/DataTypes/S3.cs
MergerLogic/DataTypes/TMS.cs
MergerLogic/DataTypes/WMTS.cs
MergerLogic/DataTypes/XYZ.cs
MergerLogic/Utils/DataFactory.cs
MergerLogic/Utils/IDataFactory.cs
MergerLogicUnitTests/DataTypes/FSTest.cs
MergerLogicUnitTests/DataTypes/GpkgTest.cs
MergerLogicUnitTests/DataTypes/S3Test.cs
MergerLogicUnitTests/DataTypes/TMSTest.cs
MergerLogicUnitTests/DataTypes/WMTSTest.cs
MergerLogicUnitTests/DataTypes/XYZTest.cs
MergerService/Models/Source.cs
MergerService/src/run.cs

Remove defaults from service

---

MergerLogic/DataTypes/Gpkg.cs
MergerLogic/Utils/GpkgUtils.cs
MergerLogic/Utils/IGpkgUtils.cs
MergerLogicUnitTests/DataTypes/GpkgTest.cs
MergerLogicUnitTests/Utils/GpkgUtilsTest.cs

chore: remove createIndex functionality

---

MergerLogic/MergerLogic.csproj
MergerLogic/Utils/HttpRequestUtils.cs
MergerLogic/Utils/IHttpRequestUtils.cs
MergerLogicUnitTests/Utils/HttpRequestUtilsTest.cs
MergerService/Utils/TaskUtils.cs

| Tests added     | ✔                                                                        | …

test: Add Http request Utils test

---

MergerService/Utils/ITaskUtils.cs
MergerService/Utils/TaskUtils.cs
MergerService/src/run.cs

fix(MergerService): notify overseer on task status change

---

helm/templates/configmap.yaml

fix: http s3 config

---

MergerCli/Process.cs
MergerCli/Program.cs
MergerLogic/ImageProcessing/TileMerger.cs

feat: Merge optimization

---

MergerService/appsettings.Development.json
MergerService/appsettings.json

chore: added costum log levels for http client logs

---

MergerLogicUnitTests/Clients/FileClientTest.cs

| Breaking change |✖                                                                        |
| Tests added     | ✔                                                                       |
| Chore            | ✖ …

test: added file-utils tests

---

MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Gpkg.cs
MergerLogic/ImageProcessing/ITileScaler.cs
MergerLogic/ImageProcessing/TileMerger.cs
MergerLogic/ImageProcessing/TileScaler.cs
MergerLogic/MergerLogic.csproj
MergerLogicUnitTests/DataTypes/FSTest.cs
MergerLogicUnitTests/DataTypes/GpkgTest.cs
MergerLogicUnitTests/DataTypes/S3Test.cs
MergerLogicUnitTests/DataTypes/TMSTest.cs
MergerLogicUnitTests/DataTypes/WMTSTest.cs
MergerLogicUnitTests/DataTypes/XYZTest.cs

fix: upscale opacity

---

MergerCli/IProcess.cs
MergerCli/ISourceParser.cs
MergerCli/Process.cs
MergerCli/Program.cs
MergerCli/SourceParser.cs
MergerLogic/Batching/Tile.cs
MergerLogic/Clients/FileClient.cs
MergerLogic/Clients/GpkgClient.cs
MergerLogic/Clients/HttpSourceClient.cs
MergerLogic/Clients/S3Client.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/ImageProcessing/IImageFormatter.cs
MergerLogic/ImageProcessing/ITileMerger.cs
MergerLogic/ImageProcessing/ImageFormatter.cs
MergerLogic/ImageProcessing/TileMerger.cs
MergerLogic/Utils/DataFactory.cs
MergerLogic/Utils/DataUtils.cs
MergerLogic/Utils/IPathUtils.cs
MergerLogic/Utils/PathUtils.cs
MergerLogic/Utils/UtilsFactory.cs
MergerLogicUnitTests/Clients/FileClientTest.cs
MergerLogicUnitTests/DataTypes/FSTest.cs
MergerLogicUnitTests/DataTypes/S3Test.cs
MergerLogicUnitTests/Utils/GpkgUtilsTest.cs
MergerLogicUnitTests/Utils/HttpSourceUtilsTest.cs
MergerLogicUnitTests/Utils/PathUtilsTest.cs
MergerLogicUnitTests/Utils/S3UtilsTest.cs
MergerService/Models/Task.cs
MergerService/Utils/TaskUtils.cs
MergerService/src/run.cs

chore: merge cli run in zoom order

---

MergerService/Models/Task.cs

fix: target format member naming in task

---

MergerLogic/Clients/HeartbeatClient.cs
MergerLogic/Clients/IHeartbeatClient.cs
MergerService/Program.cs
MergerService/Utils/TaskUtils.cs
MergerService/appsettings.Development.json
MergerService/appsettings.json
MergerService/src/run.cs
helm/templates/configmap.yaml
helm/values.yaml

| New feature     | ✔                                                                       |
| Chore            | ✔ …

feat: added heartbeat support for tasks

---

MergerCli/Program.cs
MergerCli/appsettings.json
MergerService/Properties/launchSettings.json

chore: add resume output location env

---

helm/templates/configmap.yaml
helm/templates/deployment.yaml
helm/values.yaml

feat: added ca-cert support

---

MergerCli/Process.cs
MergerCli/Program.cs
MergerCli/Properties/launchSettings.json
MergerCli/utils/BatchStatusManager.cs
MergerLogic/Batching/Tile.cs
MergerLogic/Clients/GpkgClient.cs
MergerLogic/Clients/IGpkgClient.cs
MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/DataTypes/Gpkg.cs
MergerLogic/DataTypes/HttpDataSource.cs
MergerLogic/DataTypes/IData.cs
MergerLogic/DataTypes/S3.cs
MergerLogic/Utils/DataFactory.cs
MergerLogic/Utils/DataUtils.cs
MergerLogic/Utils/GeoUtils.cs
MergerLogic/Utils/IDataUtils.cs
MergerLogic/Utils/IGeoUtils.cs
MergerLogicUnitTests/DataTypes/FSTest.cs
MergerLogicUnitTests/DataTypes/GpkgTest.cs
MergerLogicUnitTests/DataTypes/S3Test.cs

| Tests added     | ✔                                                                        | …

chore(cli): ignore base tiles when created

---

MergerLogic/Clients/GpkgClient.cs

chore: check if dir exists in create

---

MergerCli/Process.cs
MergerCli/appsettings.json
MergerLogic/Clients/GpkgClient.cs

feat(cli): add upload only mode

---

helm/templates/configmap.yaml

fix(helm): incorrect env's for heartbeat

---

helm/templates/configmap.yaml
helm/values.yaml

fix(helm): move heartbeat url value to different section

---

MergerService/src/run.cs

fix: handle s3 input type

---

MergerService/Utils/TaskUtils.cs

fix: job complete api

---

helm/templates/_helpers.tpl
helm/templates/configmap.yaml
helm/templates/deployment.yaml

fix: chart

---

MergerLogic/ImageProcessing/TileScaler.cs

fix(upscaling): wrong pixle used when upscaling (MAPCO-3143)

---

helm/templates/deployment.yaml

fix: revert pvc changes

---

.github/workflows/build_and_push.yml
MergerCli/Process.cs
MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/ImageProcessing/TileScaler.cs
MergerLogicUnitTests/DataTypes/FSTest.cs
MergerService/src/run.cs

fix(upsacle): dispose of allocated pixels object (MAPCO-3144)

---

MergerCli/Process.cs
MergerLogic/Clients/GpkgClient.cs
MergerLogic/Clients/HeartbeatClient.cs
MergerLogic/Clients/HttpRequestUtils.cs
MergerLogic/Clients/S3Client.cs
MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/DataTypes/Gpkg.cs
MergerLogic/DataTypes/S3.cs
MergerLogic/Utils/DataFactory.cs
MergerLogic/Utils/UtilsFactory.cs
MergerLogicUnitTests/DataTypes/S3Test.cs
MergerLogicUnitTests/Utils/S3UtilsTest.cs
MergerService/Utils/JobUtils.cs
MergerService/Utils/TaskUtils.cs
MergerService/src/run.cs

chore: add logs for timing debug

---

helm/values.yaml

enabled metrics

---

MergerLogic/Monitoring/OpenTelemetryFormattedConsoleExporter.cs

chore: Add Exception to logs

---

MergerService/Program.cs

chore: catch and log unhandled expetions

---

MergerLogic/ImageProcessing/ImageFormatter.cs

| Bug fix         | ✔                                                                       |
| Chore            | ✖ …

fix: convert to png32

---

MergerCli/appsettings.json
MergerLogic/Clients/S3Client.cs
MergerLogic/Utils/UtilsFactory.cs
MergerLogicUnitTests/Utils/S3UtilsTest.cs
MergerService/appsettings.Development.json
MergerService/appsettings.json

chore: add ability to set S3 storage class

---

MergerService/Program.cs

fix: Try limit default file watcher 

---

MergerService/Models/Tasks/Task.cs
MergerService/Utils/ITaskUtils.cs
MergerService/Utils/TaskUtils.cs
MergerService/src/run.cs

fix: max task retires logic (MAPCO-3688)

---

MergerLogic/Monitoring/Metrics/IMetricsProvider.cs
MergerLogic/Monitoring/Metrics/MetricsProvider.cs
MergerService/Runners/TaskExecutor.cs

refactor: change source building location

---

.github/workflows/build_and_push.yml

| New feature     | ✔                                                                  |
| Chore            | ✔ …

fix: upgrade git action to support auto helm registry push

---

.github/workflows/build_and_push.yml

| Bug fix         | ✔                                                                       |
| Chore            | ✖ …

fix: github action to build and push docker

---

helm/Chart.yaml

chore: upgrade helm version to match tag

---

helm/templates/configmap.yaml
helm/values.yaml

chore: added configuration for the s3 storage class (MAPCO-4127)

---

helm/Chart.yaml

chore: bumped helm chart version to 1.3.5

---

helm/Chart.yaml
helm/templates/deployment.yaml

fix: volumeMonuts fix (MAPCO-4136)

---

MergerCli/Process.cs
MergerLogic/Clients/GpkgClient.cs
MergerLogic/Clients/S3Client.cs
MergerLogic/DataTypes/Data.cs
MergerLogic/DataTypes/Fs.cs
MergerLogic/DataTypes/Gpkg.cs
MergerLogic/DataTypes/S3.cs
MergerLogic/ImageProcessing/TileMerger.cs
MergerLogic/Monitoring/OpenTelemetryFormattedConsoleExporter.cs
MergerLogic/Utils/DataFactory.cs
MergerLogic/Utils/DataUtils.cs

refactor: fix null reference warnings

---

helm/templates/configmap.yaml

fix: fix underscores in configmaps

---

helm/Chart.yaml

chore: update helm version to 1.3.8

---

helm/Chart.yaml

chore: bump helm version to 1.4.0
